using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assignment.Model
{
    // A class that represents an object generated by the API

    class User
    {
        public int ID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Email { get; set; }
        public String Gender { get; set; }
        public String IPAddress { get; set; }

        public override string ToString()
        {
            return String.Format("{0}, {1} {2} ({4}), {3} / {5}", ID, FirstName, LastName, Email, Gender, IPAddress);
        }
    }
}
